### ISSUE TITLE
Non-stop Reload

### ISSUE THREAD

**Issue by sammkj** [gadicc/meteor-react-hotloader#22] opened 2016-03-31 18:48 UTC
This is probably not something important. If any changes happen in the `public` folder, the app will reload non-stop.

**Comment by gadicc** [comment] 2016-04-01 06:58
Thanks for the report.

This seems to be caused by a bug in Meteor (that gets amplified by this package).  I'll investigate further and try make a simplified reproduction to send to Meteor over the next few days.

The more "both" files you have (files that are loaded on both the client and server), the worse this issue is, as Meteor seems to think that server files have changed when `public` does, and this package acts on any changes to client files -- files in "both" folders share this attribute.

**Comment by sammkj** [comment] 2016-04-01 18:53
This issue only happens when I edit .css files in the public folder.

woah. I didn't know the side-effect of having too many shared files! Thanks for letting me know.

**Comment by gadicc** [comment] 2016-04-01 19:14
It's only such a big issue here because it affects the reloading... without this package, it would just mean reloads take slightly longer than they would otherwise... but I still need to investigate properly.

**Comment by gadicc** [comment] 2016-04-02 09:16
My bad.  Totally my fault.  Fixed in `gadicc:ecmascript-hot@1.3.0_5` (just remove the @version and `meteor update` now).

**Comment by sammkj** [comment] 2016-04-03 04:11
thanks for fixing this! i can confirm this issue is gone.

**Comment by gadicc** [comment] 2016-04-04 18:22
Awesome.  Thanks as always for reporting back.

**Closed by gadicc** 2016-04-04 18:22 UTC
