### ISSUE TITLE
.babelrc not found in test mode

### ISSUE THREAD

**Issue by dominikmayer** [gadicc/meteor-react-hotloader#37] opened 2016-04-13 20:36 UTC
When I run

    meteor test --driver-package practicalmeteor:mocha --port 3010

Meteor complains that it doesn't find a `.babelrc` file:

```
I20160413-01:51:38.332(2)? Creating /private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/client/.babelrc
W20160413-01:51:38.333(2)? (STDERR)           
W20160413-01:51:38.334(2)? (STDERR) /Users/dominik/.meteor/packages/meteor-tool/.1.3.1.oynoy3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160413-01:51:38.335(2)? (STDERR)             				throw(ex);
W20160413-01:51:38.335(2)? (STDERR)             				      ^
W20160413-01:51:38.344(2)? (STDERR) Error: ENOENT, no such file or directory '/private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/client/.babelrc'
W20160413-01:51:38.344(2)? (STDERR)     at Object.fs.openSync (fs.js:439:18)
W20160413-01:51:38.345(2)? (STDERR)     at Object.fs.writeFileSync (fs.js:978:15)
W20160413-01:51:38.345(2)? (STDERR)     at hot.lastHash (packages/gadicc_babel-compiler-hot.js:88:8)
W20160413-01:51:38.345(2)? (STDERR)     at packages/gadicc_babel-compiler-hot.js:190:4
W20160413-01:51:38.345(2)? (STDERR)     at packages/gadicc_babel-compiler-hot.js:625:3
W20160413-01:51:38.345(2)? (STDERR)     at /private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/.meteor/local/build/programs/server/boot.js:283:10
W20160413-01:51:38.346(2)? (STDERR)     at Array.forEach (native)
W20160413-01:51:38.346(2)? (STDERR)     at Function._.each._.forEach (/Users/dominik/.meteor/packages/meteor-tool/.1.3.1.oynoy3++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160413-01:51:38.346(2)? (STDERR)     at /private/var/folders/73/1m3gx4_56hlf6vtj8rbt19qw0000gn/T/meteor-test-rundcrtvh/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8             
```

I do have a `.babelrc` file in my project root and running the command created another one in my `client` folder.

Over at the [Meteor Mocha](https://github.com/practicalmeteor/meteor-mocha/issues/30) project they referred to this package.

Everything works when I run `meteor`. The problems only appear in test mode.

Any ideas on how to fix this?

**Comment by jbbr** [comment] 2016-04-13 22:32
I can confirm this issue. Really annoying as I depend on this package (some es6 features enabled in babelrc) and can't just replace it with the original "ecmascript" package.

Otherwise a really great package which allowed me to switch from webpack to plain meteor build.
Hopefully there will be a fix soon.

**Comment by jbbr** [comment] 2016-04-13 23:40
The problem seems to be in how the project root path is detected in "babel-compiler-hot" module. https://github.com/gadicc/meteor-react-hotloader/blob/master/babel-compiler-hot/babelrc.js#L46
It's already with a commend asking for a better way to do this.

The problem: This does work in dev- and production modes but not in testing mode. In testing mode the projectRoot which is detected is a temporary directory for the separated testing environment.

I did a little research and it looks like on Linux and OSX the real project path is available in the "PWD" environment variable. So this whole detection code could be replaced by a simple `process.env.PWD`.
Unfortunately this is probably not possible on Windows.

**Comment by gadicc** [comment] 2016-04-14 06:23
Hey guys, this is a dupe of #27 but I'll continue to track it here because there is more information - on that note, thanks @jbbr for all the research!

PWD is just the present working directory, it's the same as CWD.  It's not good enough for projRoot detection (try run `meteor` from a subdirectory of your project), *but*, it sounds like it is good enough for use in test mode (which we can detect), so it sounds like this will be the path for our fix, and to disable the hotloading.

In the meantime, to disable the hotloading, just set `BABEL_ENV=production`.

I'll address this in a release as soon as I can, thanks for the help.

**Comment by gadicc** [comment] 2016-04-14 09:35
Can anyone let me know how `ecmascript-hot@1.3.1-fast.9` performs?

I didn't fix the path issue but between disabling some other stuff for tests and other changes I made earlier in the week, I can't seem to reproduce this on my side, but I think it's more likely from my setup. If the problem still exists would love if someone could share a repo.  Thx.

**Comment by jbbr** [comment] 2016-04-14 12:01
Thanks a lot, `ecmascript-hot@1.3.1-fast.9` seems to fix the issue. I first struggled with upgrading to it as Meteors versioning systems expects `1.3.1_1` to be a higher version then `1.3.1-fast.9`.
But pinning the exact version in packages file does work: `gadicc:ecmascript-hot@=1.3.1-fast.9` Setting `BABL_ENV` is not required.

btw: `process.env.PWD` is NOT the same as `process.cwd()` in Meteor`s testing environment during build. The former returns the project path like `/Users/user/dev/myproject`, the latter returns the temporary testing path - something like `/private/var/folders/<random>/...`.

One more question: Could you provide some hints for contributors who want to build your packages from git? I struggled with cloning master and symlinking the packages to my packages directory. Couldn't get it to work due to various errors. Also I couldn't find the `fast.9` build in git.

**Comment by gadicc** [comment] 2016-04-14 13:14
No, that was unintentional.  I'm actually surprised `.9` worked at all :)  The `isTest()` code got amended a few times and my final version was actually broken, but has been fixed now.  Can you confirm if `ecmascript-hot@=1.3.1-fast.10` still solves this?  The accelerator won't start in test mode now.

Your message contained a lot of useful info!  Thanks for all this.

Re `process.env.PWD`, thanks pointing this out... it's something I never would have thought to check (but should have).  Yes - `process.env.PWD` is the CWD that the initial node process was started in, and remains static... `process.cwd()` will reflect any `process.chdir()` changes, etc.  And I'm not even sure about child_process's with a custom CWD.  In the case of testing, also not sure what the PWD will be if the user launches `meteor test` from a subdirectory of their projRoot... I'll check if we ever need this all again.

Excellent remark about CONTRIBUTING, I've added a draft file for this now, and covered some of the conversioning too (since this will only ever affect experimental and test releases).  Up until recently I wasn't even sure if more than 4 people were using this... things kinda exploded about Meteor 1.3 final came out :>  Thanks for all the help today!

**Comment by jbbr** [comment] 2016-04-14 13:37
Confirmed, `ecmascript-hot@=1.3.1-fast.10` still solves this. Thanks!

Also thank you for adding the CONTRIBUTING guide. I came across this package while using `thereactivestack/webpack` for a project of mine. Unfortunately I had some issues with this webpack/meteor integration especially with debugging, source-maps and testing.
That's why I wanted to give plain Meteor 1.3 a try and with your package I could continue to benefit from both hot reloading and additional babel transforms.

As react hot-reload and additional language features by using babel are quite popular, I think that your package will gain in popularity if it continues to work well.
Though I still hope, that .babelrc support will be added to Meteor 1.3.x soon.

**Comment by gadicc** [comment] 2016-04-14 13:56
Great stuff!  Thanks for reporting back.

Yes, as far as I know the `.babelrc` support will make it into one of the 1.3.x releases.  I expect a lot of the code that's been developed here for that will be contributed back, or at least used strongly for reference.  As you've seen there have been quite a few Meteor specific issues which I've gradually been solving thanks to user reports... and this is something Meteor will benefit from.

And one day I'll do sourcemap support for even the hot reloading... but for now a ctrl-R does the trick for when we really need this :>

Thanks again for the help.

**Closed by gadicc** 2016-04-14 13:56 UTC

**Comment by jbbr** [comment] 2016-04-14 14:19
For others having issue with this:

Settings `BABEL_ENV=production` during tests IS indeed required if you want to test React components while having `react-transform-hmr` enabled in your clients .babelrc.
Otherwise hmr-transforms will cause errors during tests.

**Comment by gadicc** [comment] 2016-04-14 15:13
We should probably actually do this by default.  I'll track in #38.

**Comment by clayne11** [comment] 2016-04-15 18:13
This is still not working for me. I see the following when I try to run package unit tests:

```
I20160415-14:11:22.246(-4)? Creating /private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1ff2ixh/.babelrc
I20160415-14:11:22.634(-4)? Creating /private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1ff2ixh/client/.babelrc
W20160415-14:11:22.635(-4)? (STDERR)
W20160415-14:11:22.635(-4)? (STDERR) /Users/clayne/.meteor/packages/meteor-tool/.1.3.2.1ki5fk2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160415-14:11:22.635(-4)? (STDERR)            				throw(ex);
W20160415-14:11:22.635(-4)? (STDERR)            				      ^
W20160415-14:11:22.636(-4)? (STDERR) Error: ENOENT, no such file or directory '/private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1ff2ixh/client/.babelrc'
W20160415-14:11:22.636(-4)? (STDERR)     at Object.fs.openSync (fs.js:439:18)
W20160415-14:11:22.636(-4)? (STDERR)     at Object.fs.writeFileSync (fs.js:978:15)
W20160415-14:11:22.636(-4)? (STDERR)     at hot.lastHash (packages/gadicc_babel-compiler-hot/babelrc.js:65:1)
W20160415-14:11:22.636(-4)? (STDERR)     at packages/gadicc_babel-compiler-hot/babelrc.js:163:1
W20160415-14:11:22.636(-4)? (STDERR)     at packages/gadicc_babel-compiler-hot/babel-compiler.js:137:1
W20160415-14:11:22.636(-4)? (STDERR)     at /private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1ff2ixh/.meteor/local/build/programs/server/boot.js:283:10
W20160415-14:11:22.637(-4)? (STDERR)     at Array.forEach (native)
W20160415-14:11:22.637(-4)? (STDERR)     at Function._.each._.forEach (/Users/clayne/.meteor/packages/meteor-tool/.1.3.2.1ki5fk2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160415-14:11:22.637(-4)? (STDERR)     at /private/var/folders/5d/7cyh0l9s72z9xqsyjwfrz0cw0000gn/T/meteor-test-run1ff2ixh/.meteor/local/build/programs/server/boot.js:133:5
```

**Comment by clayne11** [comment] 2016-04-15 20:09
It looks like `client/.babelrc` is created only if a `client` directory already exists. If it doesn't, the parent (`client`) directory is never created and neither is `client/.babelrc`.

**Comment by clayne11** [comment] 2016-04-15 20:37
I created a PR to fix this https://github.com/gadicc/meteor-react-hotloader/pull/39

**Comment by gadicc** [comment] 2016-04-16 09:36
d'oh I also changed one of the tests recently to figure out if we're in test mode by looking for a 'test' arg.  I need to look for 'test-packages' too.
